export const meals = {
  healthy: [
    { name: "Grilled Chicken Salad" },
    { name: "Paneer Salad Bowl" },
    { name: "Quinoa Veggie Bowl" },
    { name: "Sprouts Chaat" },
    { name: "Vegetable Stir Fry" },
    { name: "Oats & Banana Bowl" },
    { name: "Green Smoothie Bowl" },
    { name: "Lemon Herb Grilled Fish" },
    { name: "Roasted Veggie Plate" },
    { name: "Avocado Toast with Eggs" },
  ],

  indian: [
    { name: "Paneer Butter Masala" },
    { name: "Masala Dosa" },
    { name: "Chole Bhature" },
    { name: "Rajma Chawal" },
    { name: "Aloo Paratha" },
    { name: "Veg Biryani" },
    { name: "Dal Tadka & Rice" },
    { name: "Idli Sambar" },
    { name: "Pav Bhaji" },
    { name: "Chicken Tikka" },
  ],

  dessert: [
    { name: "Chocolate Brownie" },
    { name: "Gulab Jamun" },
    { name: "Ice Cream Sundae" },
    { name: "Mango Pudding" },
    { name: "Cheesecake Slice" },
    { name: "Cupcake Trio" },
    { name: "Warm Chocolate Lava Cake" },
    { name: "Oreo Milkshake" },
    { name: "Fruit Custard" },
    { name: "Apple Pie" },
  ],

  snack: [
    { name: "Veg Sandwich" },
    { name: "Bhel Puri" },
    { name: "Hummus & Chips" },
    { name: "Garlic Bread" },
    { name: "Peanut Chaat" },
    { name: "Nachos & Salsa" },
    { name: "Masala Corn Cup" },
    { name: "Cheese Toast" },
    { name: "Fruit Bowl" },
    { name: "Popcorn Bowl" },
  ],

  highProtein: [
    { name: "Grilled Chicken Breast" },
    { name: "Egg Omelette Wrap" },
    { name: "Protein Smoothie" },
    { name: "Paneer Scramble" },
    { name: "Tofu Stir Fry" },
    { name: "Chicken & Veggies Plate" },
    { name: "Lentil Soup Bowl" },
    { name: "Egg & Avocado Bowl" },
    { name: "Greek Yogurt Bowl" },
    { name: "Tuna Sandwich" },
  ],
};